# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

H <- function(A) {
    .Call(`_Rfssa_H`, A)
}

#'@importFrom Rcpp sourceCpp
HLinprod <- function(x, y, G) {
    .Call(`_Rfssa_HLinprod`, x, y, G)
}

#'@importFrom Rcpp sourceCpp
HpLinprod <- function(X, Y, G, p) {
    .Call(`_Rfssa_HpLinprod`, X, Y, G, p)
}

#' @importFrom Rcpp sourceCpp
#' @useDynLib Rfssa, .registration = TRUE
NULL

#' @importFrom Rcpp sourceCpp
NULL

#'@importFrom Rcpp sourceCpp
NULL

#' @importFrom Rcpp sourceCpp
NULL

#'@importFrom Rcpp sourceCpp
NULL

#'@importFrom Rcpp sourceCpp
NULL

#'@importFrom Rcpp sourceCpp
Cofmat <- function(d, L, cx) {
    .Call(`_Rfssa_Cofmat`, d, L, cx)
}

#'@importFrom Rcpp sourceCpp
SS <- function(K, L, B, d) {
    .Call(`_Rfssa_SS`, K, L, B, d)
}

#'@importFrom Rcpp sourceCpp
SSM <- function(K, L, d_tilde, p, B, shifter) {
    .Call(`_Rfssa_SSM`, K, L, d_tilde, p, B, shifter)
}

#'@importFrom Rcpp sourceCpp
Gramm <- function(K, L, p, d_tilde, A, shifter, d) {
    .Call(`_Rfssa_Gramm`, K, L, p, d_tilde, A, shifter, d)
}

#'@importFrom Rcpp sourceCpp
mwinprod <- function(X, Y, w, G, p) {
    .Call(`_Rfssa_mwinprod`, X, Y, w, G, p)
}

#'@importFrom Rcpp sourceCpp
winprod <- function(x, y, w, G) {
    .Call(`_Rfssa_winprod`, x, y, w, G)
}

