# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

H <- function(A) {
    .Call('_Rfssa_H', PACKAGE = 'Rfssa', A)
}

#' @importFrom Rcpp sourceCpp
mod <- function(K, W) {
    .Call('_Rfssa_mod', PACKAGE = 'Rfssa', K, W)
}

#' @importFrom Rcpp sourceCpp
Csij <- function(i, j, K, L, B) {
    .Call('_Rfssa_Csij', PACKAGE = 'Rfssa', i, j, K, L, B)
}

#'@importFrom Rcpp sourceCpp
SS <- function(K, L, B, d) {
    .Call('_Rfssa_SS', PACKAGE = 'Rfssa', K, L, B, d)
}

#'@importFrom Rcpp sourceCpp
Cofmat <- function(d, L, cx) {
    .Call('_Rfssa_Cofmat', PACKAGE = 'Rfssa', d, L, cx)
}

#'@importFrom Rcpp sourceCpp
Gram <- function(K, L, A, d) {
    .Call('_Rfssa_Gram', PACKAGE = 'Rfssa', K, L, A, d)
}

